spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://seose11.iptime.org:13306/test?autoReconnect=true&useSSL=false
    username: root2
    password: 1111
    hikari:
      auto-commit: true
      pool-name: hackathon
      register-mbeans: true
      minimum-idle: 5
      maximum-pool-size: 5
      connection-test-query: select 1
      connection-timeout: 3200
      validation-timeout: 3200
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb


