spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&mysqlEncoding=utf8&connectTimeout=5000&socketTimeout=5000&useServerPrepStmts=true&cachePrepStmts=true&useSSL=false
    username: root
    password: 1234
    hikari:
      auto-commit: true
      pool-name: hackathon
      register-mbeans: true
      minimum-idle: 5
      maximum-pool-size: 5
      connection-test-query: select 1
      connection-timeout: 3200
      validation-timeout: 3200
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb


